//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCovidStat.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class VacDBEntities : DbContext
    {
        public VacDBEntities()
            : base("name=VacDBEntities")
        {
        }
        
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
            //modelBuilder.Entity<VacPerson>()
            //    .Property(e => e.Vaccine)
            //    .HasConversion();
        }
    
        public virtual DbSet<VacPerson> Vacced { get; set; }
    }   
}
