//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCovidStat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacPerson
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime Birthday { get; set; }
        public string City { get; set; }
        public System.DateTime DayOfVaccination { get; set; }
        public string Vaccine { get; set; }
        public int VaccineDose { get; set; }
    }
}
